### PR TITLE
Class 2 again commited for PR approve

### PR DESCRIPTION
**Pull request by fahimar**
I have updated and add some practice but previous PR request comparing changes has lost. Again I am creating a pull request.

### CODE REVIEW

**Comment by tajnur007** [comment]
Bro, I think you should do more practice on each part of Class 2. Do you think I should approve? Or do you want to add more practices? Well, if you want then I can approve.

**Comment by fahimar** [comment]
I need to practice more. I will make a pull request later again.

**Comment by tajnur007** [comment]
Good decision. No need to close this PR, nor merge it. Just do your practice, do commit & push it and when you will finished your practice, just ping me in our Whatsapp group, I will then take a look into it. Thanks!

**Review by tajnur007 — APPROVED** [review]
Good practice Bro. Keep it up.
Approved from my side!

**Comment by fahimar** [comment]
Thank you. I will practice more.

**Pull request merged**
